# Generated by Django 6.0 on 2025-12-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='birthday',
            new_name='comment',
        ),
    ]
