# Generated by Django 3.2.16 on 2025-12-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_birthday_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='post',
        ),
    ]
